name: release

on:
  watch:
    types: [started]
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v2
          path: alist-web
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          repository: alist-org/assets
          ref: main
          path: assets
          persist-credentials: false
          fetch-depth: 0

      - name: Build
        run: |
          mv alist-web/build.sh .
          bash build.sh
      
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          tag_name: Auto-${{ steps.create_timestamp.outputs.timestamp }}
          release_name: Release-${{ steps.create_timestamp.outputs.timestamp }}
          body: ${{ steps.tag_version.outputs.changelog }}
